name: gateway
namespace: erlendum

replicaCount: 1

image:
  repository: elrendum/rsoi-lab-02-gateway
  tag: latest

postgresql:
  dsn: ""

services:
  library-system: ""
  rating-system: ""
  reservation-system: ""

port: 80